name: Build Docker Image
on:
  push:
    branches:
      - dockerfile
jobs:
    build:
      name: push docker image to docker hub
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: login to docker hub
          id: docker-hub
          run: |
            echo ${{secrets.DOCKERHUB_PASSWORD}} | docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-stdin
        - name: build the docker image
          id: build-docker-image
          run: |
            ls -la 
            docker build . -f docker/Dockerfile -t ${{secrets.DOCKERHUB_USERNAME}}/academic-writing:latest
        - name: push the docker image
          id: push-docker-image
          run: docker push ${{secrets.DOCKERHUB_USERNAME}}/academic-writing:latest
