name: compile on release

on: release

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-20.04
    container: 
      image: philkohn/academic-writing:latest

    steps:
      - uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: output/output.pdf
