name: compile on release

on: release

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-20.04
    container: 
      image: philkohn/academic-writing:latest

    steps:
      # checkout repo contents
      - uses: actions/checkout@v4
      - name: run build.sh
        run: ./build.sh
      - name: get output
        shell: bash
        run: cat output.pdf
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: output.txt
