name: compile on release

on: release

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
      - name: Run Docker container without AppArmor
        run: docker run --security-opt apparmor=unconfined philkohn/academic-writing:latest
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: output/output.pdf
