name: compile on release

on: release

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-20.04

    steps:
      # checkout repo contents
      - uses: actions/checkout@v4
      - uses: docker://philkohn/academic-writing:latest
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: /github/workspace/output/output.pdf
